# Generated by Django 3.1.2 on 2020-11-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_jabatan', models.CharField(max_length=200, null=True)),
                ('jabatan', models.CharField(max_length=200, null=True)),
                ('tmt_jabatan', models.CharField(max_length=200, null=True)),
                ('mk_tahun', models.IntegerField()),
                ('mk_bulan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_pangkat', models.CharField(max_length=200, null=True)),
                ('pangkat', models.CharField(max_length=200, null=True)),
                ('tmt_pangkat', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_pendidikan', models.CharField(max_length=200, null=True)),
                ('nama_pendidikan', models.CharField(max_length=200, null=True)),
                ('jurusan', models.CharField(max_length=200, null=True)),
                ('tingkat_pendidikan', models.CharField(max_length=200, null=True)),
                ('tahun_lulus', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('golongan', models.CharField(max_length=200, null=True)),
                ('tempat_lahir', models.CharField(max_length=200, null=True)),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('agama', models.CharField(max_length=200, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('kd_jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.jabatan')),
                ('kd_pangkat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.pangkat')),
                ('kd_pendidikan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.pendidikan')),
            ],
        ),
    ]
