# Generated by Django 3.1.2 on 2020-11-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='kd_pangkat',
        ),
        migrations.DeleteModel(
            name='Pangkat',
        ),
    ]
